# Generated by Django 4.0.5 on 2022-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_id_alter_post_user_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
