# Generated by Django 4.0.5 on 2022-06-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_id_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='', max_length=180),
        ),
    ]
